# Generated by Django 5.1.7 on 2025-03-31 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('no_of_available_item', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BuyingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_item', models.IntegerField()),
                ('price_of_one_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rupees', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_transactions', to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='SellingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_item', models.IntegerField()),
                ('price_of_one_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rupees', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_transactions', to='inventory.item')),
            ],
        ),
    ]
